# Generated by Django 5.1.5 on 2025-02-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="is_redeemed",
            field=models.BooleanField(default=False),
        ),
    ]
