# Generated by Django 5.1.5 on 2025-02-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalvault",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
