# Generated by Django 5.1.5 on 2025-02-04 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_personalvault_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="challenge_type",
            field=models.CharField(
                choices=[
                    ("WEEKLY", "Weekly"),
                    ("MONTHLY", "Monthly"),
                    ("CUSTOM", "Custom"),
                ],
                default="CUSTOM",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="is_automated",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="UserPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_contributions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "weekly_contributions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "monthly_contributions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("last_challenge_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
