# Generated by Django 5.1.5 on 2025-02-08 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_expense_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="challenge",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="user",
        ),
        migrations.RemoveField(
            model_name="moneyvault",
            name="author",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="vault",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="user",
        ),
        migrations.DeleteModel(
            name="Challenge",
        ),
        migrations.DeleteModel(
            name="Expense",
        ),
        migrations.DeleteModel(
            name="MoneyVault",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
