# Generated by Django 5.1.5 on 2025-02-25 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("challenges", "0001_initial"),
        ("vaults", "0005_alter_moneyvaultdata_contribution_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("CHALLENGE_CONTRIBUTION", "Challenge Contribution"),
                            ("CHALLENGE_REFUND", "Challenge Refund"),
                            ("VAULT_CONTRIBUTION", "Vault Contribution"),
                            ("VAULT_REFUND", "Vault Refund"),
                        ],
                        max_length=25,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("vault_title", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="challenges.challenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vault",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vaults.moneyvault",
                    ),
                ),
            ],
        ),
    ]
