# Generated by Django 5.1.5 on 2025-02-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="challenge_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="vault_title",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
