# Generated by Django 5.1.5 on 2025-02-09 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MoneyVault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "current_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("description", models.TextField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaults",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
