# Generated by Django 5.1.5 on 2025-02-11 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vaults", "0002_moneyvault_is_redeemed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="moneyvault",
            old_name="author",
            new_name="user",
        ),
    ]
