# Generated by Django 5.1.5 on 2025-02-13 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vaults", "0003_rename_author_moneyvault_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoneyVaultData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                (
                    "contribution_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                (
                    "vault",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_data",
                        to="vaults.moneyvault",
                    ),
                ),
            ],
            options={
                "ordering": ["-month"],
                "unique_together": {("vault", "month")},
            },
        ),
    ]
