name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: vaulet-db
          POSTGRES_USER: mishti
          POSTGRES_PASSWORD: mishti123
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          
      - name: Install Dependencies
        run: cd frontend && npm install
        
      - name: Build Project
        run: cd frontend && npm run build
        
      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./frontend/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./frontend/dist
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CI_CD_TOKEN }}
          publish_dir: ./frontend/dist
